name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    name: Build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Python tools
        run: |
          python -m pip install --upgrade pip setuptools build wheel
      - name: Build
        run: |
          python -m build
      - name: Publish to PyPI
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
